apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: order-management-cluster
  region: us-west-2
  version: "1.34"
  tags:
    Environment: development
    Application: order-management-api

# EKS AutoMode configuration
# AutoMode automatically manages EC2 instances, compute autoscaling,
# pod networking, load balancing, storage, and cluster DNS
autoModeConfig:
  enabled: true
  # Optional: Leave nodePools unspecified to use default node pools
  # (general-purpose and system). To disable default node pools, set to []
  # nodePools: []
  # Optional: eksctl will create a node role if not specified
  # nodeRoleARN: arn:aws:iam::ACCOUNT_ID:role/eksctl-order-management-cluster-NodeInstanceRole

# IAM configuration
iam:
  withOIDC: true
  # Note: EKS AutoMode includes built-in load balancer management,
  # so we don't need a service account for AWS Load Balancer Controller

# VPC configuration - optimized for development
# Using Single NAT gateway instead of HighlyAvailable to reduce costs
vpc:
  cidr: "10.0.0.0/16"
  nat:
    gateway: Single

# CloudWatch logging - minimal for development
# Only enable essential log types to reduce costs
cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit"]
